### ISSUE TITLE
Fuel log tracking

### ISSUE THREAD

**Issue by jantman** [jantman/biweeklybudget#87]
Add a feature for tracking fuel fills on vehicles.

- [x] Supports multiple vehicles with a default
- [x] Graph of fuel economy per vehicle
- [x] Graph of fuel prices over time
- [x] Display datatable
- [x] Input modal with notes, as well as option to create a Transaction for the fill
