### ISSUE TITLE
BoM tracking for projects

### ISSUE THREAD

**Issue by jantman** [jantman/biweeklybudget#88]
Add ability to track lists of required items and their cost for projects, i.e. a Bill of Materials (BoM).

- [x] Multiple projects, active/inactive
- [x] Materials entries per project, with description, quantity, unit cost, total cost
- [x] Mark items as purchased
- [x] Show projects with total cost, purchased, remaining cost
